### ISSUE TITLE
Gradius Enemies spawning in events as well

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [cheeeeeeeeeen/Chens-Gradius-Mod#216]
> Though I just discovered a bug that you might want to patch in the future versions: gradius enemies are spawning during moon events (pumpkin moon in this case), and from previous comments I've been reading they seem to be spawning during other events too, and very often due to highly increased spawn rates

\- [IDGCaptainRussia](https://forums.terraria.org/index.php?members/idgcaptainrussia.104197/)

The enemies should not spawn in events.

**Comment by MichaelTheAvali** [comment]
They also spawn at the town/where you make your home, killing your NPCs and i'm unsure if this should happen

**Comment by cheeeeeeeeeen** [comment]
Noted. It shouldn't.

**Comment by cheeeeeeeeeen** [comment]
This issue is addressed. Closing. Please reopen if issue persists.
