### ISSUE TITLE
Config option to adjust the spawn rates of enemies

### ISSUE THREAD

**Issue by bigyihsuan** [cheeeeeeeeeen/Chens-Gradius-Mod#220]
I've played with this mod for a while now in my super modded worlds (once post-Moon Lord, one in progress post-Mechanical Bosses), and my biggest gripe are the enemies that spawn after Wall of Flesh is killed.

It's super annoying since the enemies travel through blocks, making it hard to defend the base from them killing my NPCs though contact or bullet damage. I had to install a mod that makes NPCs immortal so that this can't happen.

Can there be a config option to toggle the enemy spawning? Or at least an option to decrease the damage of them?

**Comment by cheeeeeeeeeen** [comment]
There's a bug fix regarding that, since the 1.0.5 version had a bug regarding their spawning. During those times you played, the mod was spawning them when you're in town.

**Comment by bigyihsuan** [comment]
I have v1.1 and still getting them spawning while in town.

**Comment by cheeeeeeeeeen** [comment]
Noted. I'll probably not do config options, though.  I'll just have them deal significantly lower damage to Town NPCs. Would that be okay?

**Comment by bigyihsuan** [comment]
disregard, might be on an outdated version

**Comment by bigyihsuan** [comment]
However, a config option would be nice.

**Comment by cheeeeeeeeeen** [comment]
I will close this issue, and open a new suggestion issue for you as I have thought a more suitable solution.

**Comment by bigyihsuan** [comment]
An additional factor is performance. My modded install is middling at best (~20 fps on average), which lately has been dropping to an unplayable <=5 whenever specifically Gradius enemies come on screen. My guess is the combination of large number of enemies spawning and the number of bullets being spawned by those enemies just tanks the frame rate when they spawn.

**Comment by cheeeeeeeeeen** [comment]
I already added a config option. Stay tuned for the next update.

**Comment by cheeeeeeeeeen** [comment]
Updated the title name for its new purpose and reopened the issue.
