### ISSUE TITLE
Embryo Spawn Spam

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [cheeeeeeeeeen/Chens-Gradius-Mod#245]
Source: https://discord.com/channels/103110554649894912/436261997416546305/868836556092370944

It happens in Singleplayer.

**Comment by Legatonin** [comment]
Additional information, it's the Unreal Modifier only on the Deadlock Gun itself causing the spawn spam bug. The glyph doesn't affect it.

Video for proof https://youtu.be/7zkBqJnX-Ow

**Comment by cheeeeeeeeeen** [comment]
I guess I would close this issue. I cannot make a specific fix for a generic implementation.
